name = "ai-agent-team"
main = "src/main/js/index.ts"
compatibility_date = "2024-01-01"

# ==========================================
# Custom Domain Configuration
# ==========================================
# Primary API endpoint: api.shyangtsuen.xyz
# Admin interface: admin.shyangtsuen.xyz (future)
# Knowledge base: kb.shyangtsuen.xyz (future)

# ==========================================
# Workers Configuration
# ==========================================
[vars]
ENVIRONMENT = "development"
LOG_LEVEL = "info"
DOMAIN = "shyangtsuen.xyz"

# ==========================================
# D1 Database Bindings
# ==========================================
[[d1_databases]]
binding = "DB"
database_name = "ai-agent-db"
database_id = "99db8f91-db78-451a-bdc8-75dd2cf3f25b"

# ==========================================
# Vectorize Bindings (for RAG)
# ==========================================
[[vectorize]]
binding = "VECTORIZE"
index_name = "ai-agent-vectors"

# ==========================================
# R2 Storage Bindings
# ==========================================
# Note: R2 needs to be enabled in Cloudflare Dashboard first
# Uncomment when R2 is enabled:
# [[r2_buckets]]
# binding = "STORAGE"
# bucket_name = "ai-agent-files"

# ==========================================
# KV Namespace Bindings (for caching)
# ==========================================
[[kv_namespaces]]
binding = "CACHE"
id = "ac78ef75b22f417d806008d1c948d33e"

# ==========================================
# Queue Bindings (for task processing)
# ==========================================
# Note: Queues require Workers Paid plan
# Uncomment when upgraded:
# [[queues.producers]]
# binding = "TASK_QUEUE"
# queue = "ai-agent-tasks"
#
# [[queues.consumers]]
# queue = "ai-agent-tasks"
# max_batch_size = 10
# max_batch_timeout = 30

# ==========================================
# Cron Triggers (for scheduled tasks)
# ==========================================
# Note: Cron triggers require Workers Paid plan ($5/month)
# DISABLED - Using NAS cron jobs instead for free alternative
# To enable: Uncomment below and upgrade to Workers Paid plan
#
# [triggers]
# crons = [
#   "*/5 * * * *",   # Database sync every 5 minutes
#   "*/30 * * * *",  # Task distribution every 30 minutes
#   "0 2 * * *",     # Daily full backup at 2 AM
#   "0 */6 * * * ",  # R2 sync every 6 hours
# ]

# ==========================================
# Build Configuration
# ==========================================
[build]
command = "npm run build"

# ==========================================
# Development Configuration
# ==========================================
[env.development]
vars = { ENVIRONMENT = "development", LOG_LEVEL = "debug" }

[[env.development.d1_databases]]
binding = "DB"
database_name = "ai-agent-db-dev"
database_id = "ad1c82b8-d27a-4a48-9a4b-e72fa8b31eec"

# ==========================================
# Production Configuration
# ==========================================
[env.production]
name = "ai-agent-team-prod"
vars = { ENVIRONMENT = "production", LOG_LEVEL = "info", DOMAIN = "shyangtsuen.xyz" }

# Custom domain routes for production
# After deployment, run: npx wrangler deployments domains add api.shyangtsuen.xyz
routes = [
  { pattern = "api.shyangtsuen.xyz/*", zone_name = "shyangtsuen.xyz" }
]

[[env.production.d1_databases]]
binding = "DB"
database_name = "ai-agent-db-prod"
database_id = "your-prod-database-id-here"

# ==========================================
# Staging Configuration (Optional)
# ==========================================
[env.staging]
name = "ai-agent-team-staging"
vars = { ENVIRONMENT = "staging", LOG_LEVEL = "debug", DOMAIN = "shyangtsuen.xyz" }

routes = [
  { pattern = "api-staging.shyangtsuen.xyz/*", zone_name = "shyangtsuen.xyz" }
]

[[env.staging.d1_databases]]
binding = "DB"
database_name = "ai-agent-db-dev"
database_id = "ad1c82b8-d27a-4a48-9a4b-e72fa8b31eec"

# ==========================================
# Limits and Performance
# ==========================================
limits = { cpu_ms = 50000 }
